Better read text

diff --git a/run b/run
--- a/run
+++ b/run
@@ -17,11 +17,13 @@ if [[ $# -ne 1 ]]; then
 fi
 
 DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-cd $DIR
 
-SRC=src
-BIN=bin
+SOLS=$DIR/src/solutions
+BIN=$DIR/bin
+FILES=$DIR/files
 NUM=$1
+
+echo $FILES
 
 if [[ $NUM = "tests" ]]; then
 
@@ -31,20 +33,20 @@ if [[ $NUM = "tests" ]]; then
     echo "Running python tests..."
     pytest
 
-elif [[ -a $SRC/p$NUM.cxx ]]; then
+elif [[ -a $SOLS/p$NUM.cxx ]]; then
 
     make $BIN/p$NUM
     echo "Running c++ solution #${NUM}..."
     $BIN/p$NUM
 
-elif [[ -a $SRC/p$NUM.py ]]; then
+elif [[ -a $SOLS/p$NUM.py ]]; then
 
     echo "Running python solution #${NUM}..."
-    python -m $SRC $NUM
+    FILES_DIR=$FILES python -m src.solutions.run_python $NUM
 
 else
 
-    >&2 echo "No solution found for '${NUM}'."
+    >&2 echo "Error: No solution found for '${NUM}'."
     show_help
     exit 1
 
